---

- name: pyats parser
  block:
  - name: "execute and parse: {{ rp_command }} using {{ rp_parser }}"   
    ansible.netcommon.cli_parse:
      command: "{{ rp_command }}"
      parser:
        name: "{{ rp_parser }}"
    register: _general
    vars:
      ansible_connection: ansible.netcommon.network_cli
  - debug: 
      var: _general.parsed
    when: rp_output == 'debug'
  tags: [general]
